JQuery_Project/urls.py
from django.contrib import admin
from django.urls import path,include
import story8_app.urls as urlStory8
import story9_app.urls as urlStory9

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(urlStory8)),
    path('story8/',include(urlStory8)),
    path('story9/',include(urlStory9)),
]

story8_app/urls.py
from django.urls import path
from .views import homepage
	#url for app
urlpatterns = [
	path('',homepage,name='beranda'),
	]

story9_app/urls.py
from django.urls import path
from .views import bukurekomen_views,subscribe_views,validasi_email,subscribe_click
	#url for app
urlpatterns = [
	path('',bukurekomen_views,name='bukurekomendasi'),
	path('validasi/<email>/',validasi_email,name='validasi'),
	path('subscribe/',subscribe_views,name='subscription'),
	path('subscribeclick/',subscribe_click,name='subsclick'),
	]

story8_app/models.py
from django.db import models

# Create your models here.

story9_app/models.py
from django.db import models
# Create your models here.
class Subscribe_model(models.Model):
	nama = models.CharField(max_length=30)
	email = models.EmailField(max_length=254)
	password = models.CharField(max_length=30)

story9_app/forms.py
from django import forms
from .models import Subscribe_model
class subscription(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())
	class Meta:
		model = Subscribe_model
		fields = ['nama','email','password']
		
		widgets ={
		'nama': forms.TextInput(attrs={'class': 'form-control','type': 'text','placeholder':'Isi nama'}),
		'email': forms.EmailInput(attrs={'class': 'form-control','type': 'text','placeholder':'Isi email'}),
		'password': forms.TextInput(attrs={'class': 'form-control','type': 'text','placeholder':'Isi password'}),

		}

		labels = {
            'nama': 'Nama Kamu',
            'email': 'Email Kamu',
            'password': 'Password Kamu',
        }

story8_app/views.py
from django.shortcuts import render
# Create your views here.
def homepage(request):
	return render(request,'myweb.html')

story9_app/views.py
import json
from django.shortcuts import render
from django.shortcuts import reverse
from django.http import HttpResponse,HttpResponseRedirect
from .forms import subscription
from .models import Subscribe_model

BOOK_API = 'https://www.googleapis.com/books/v1/volumes?q='

response = {}

# Create your views here.
def bukurekomen_views(request):
	books = json.dumps(BOOK_API)
	response['books'] = books
	return render(request,'bukumenarik.html',response)

def subscribe_views(request):
	if request.method == "POST":
		form = subscription(request.POST)
		if form.is_valid():
			agendabaru = form.save()
			return HttpResponseRedirect(reverse('subscription'))
	else:
		form = subscription()

	return render(request, 'subscribe.html', {'form': form})

def validasi_email(request,email= None):
	email_model= Subscribe_model.objects.filter(email__iexact=email).exists()
	data = {'ada': email_model}
	if data['ada']:
		data['message'] = 'Email tersebut sudah pernah didaftarkan sebelumnya, silahkan daftar dengan email lain.'
	else:
		data['message'] = 'Email belum terdaftar, silahkan daftar dengan email ini.'
	json_data = json.dumps(data)
	return HttpResponse(json_data, content_type='application/json')
def subscribe_click (request):
	if(request.method== 'POST'):
		nama = request.POST['nama']
		email = request.POST['email']
		password = request.POST['password']
		Subscribe_model.objects.create(nama=nama,email=email,password=password)
		return HttpResponse('')
	

story8_app/templates/mynavbar.html
<!DOCTYPE html>
<html>
<head>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" id="bootstrap">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Story8 & 9</title>
</head>
<body>
	<nav class="navbar navbar-inverse ">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'beranda' %}">Story 8</a>
				<a class="navbar-text" href="{% url 'bukurekomendasi' %}" style="color: white;">Rekomendasi Buku</a>
				<a class="navbar-text" href="{% url 'subscription' %}" style="color: white;">Subscribe</a>
			</div>
			<div class="navbar-right">
				<button class="btn btn-danger navbar-btn" id="button-normal" >Change  Normal Theme</button>
				<button class="btn btn-danger navbar-btn" id="button-red">Change Red Theme</button>
				<button class="btn btn-danger navbar-btn" id="button-green">Change Green Theme</button>
			</div>

		</div>
	</nav>
</body>
</html>

story8_app/templates/myweb.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<header>{% include "mynavbar.html" %}</header>
	<style type="text/css">
		.picture-main {
		  background: url("http://www.bde.enscmu.uha.fr/wp-content/uploads/2017/07/photo-header.jpg") no-repeat 50%;
		  margin-top: -21px;
		  width: 100%;
		  height: 400px;
		}
		.cover{
		  background-size: cover;
		}

		/* Style the buttons that are used to open and close the accordion panel */
		.accordion {
		    background-color: #ffffff;
		    color: #444;
		    cursor: pointer;
		    padding: 18px;
		    width: 100%;
		    text-align: left;
		    border: none;
		    outline: none;
		    transition: 0.4s;
		}

		/* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */
		.active, .accordion:hover {
		    background-color: #f41111;
		}

		/* Style the accordion panel. Note: hidden by default */
		.panel {
		    padding: 0 18px;
		    background-color: white;
		    overflow: hidden;
		}
		#container-bawah{
			background-color:red;
		}
		#loader{
			display:    block;
		    position:   fixed;
		    z-index:    1000;
		    top:        0;
		    left:       0;
		    height:     100%;
		    width:      100%;
		    background: rgba( 255, 255, 255, .8 ) 
                url('https://loading.io/spinners/rolling/lg.curve-bars-loading-indicator.gif') 
                50% 50% 
                no-repeat;
		}
		#badan-konten{
			display: none;
		}
	</style>
	<link rel="stylesheet" type="text/css" href="{% static 'mystyle.css' %}">
</head>
<body>
<div id="loader">
</div>
<div class="container-fluid picture-main cover" id="badan-konten">
	<div class="row">
		<div class="col-md-6">
			<img class= "img-circle" src="https://scontent-sin2-2.xx.fbcdn.net/v/t1.0-9/41948624_2601840056496441_3576067586867068928_n.jpg?_nc_cat=106&_nc_ht=scontent-sin2-2.xx&oh=65ff244c0d2eaa93d94f34691a450d79&oe=5C3EA650" style="width:38vh;height:35vh;margin-top: 50px;">
		</div>
		<div class="col-md-6" id="accordionku">
			<button class="accordion">Organisasi</button>
			<div class="panel">
			  <ol>
		      	<li>BPH OSIS SMAN Modal Bangsa 2016</li>
		      	<li>Staff Kreartore 2017</li>
		      	<li>Wakil Ketua Computer Science Sineas 2018</li>
		      </ol>
			</div>

			<button class="accordion">Kepanitiaan</button>
			<div class="panel">
			  <ol>
		      	<li>Staff Mentor Betis 2018</li>
		      	<li>Staff Mentor PMB 2018</li>
		      	<li>Staff Artistic Videography UIFF 2018</li>
		      	<li>BPH PHD SSG UI 2019</li>
		      </ol>
			</div>

			<button class="accordion">Pengalaman Seni</button>
			<div class="panel">
			  <ol>
		      	<li>Pemeran Utama Pementasan Teater Mosa di Flash 2016</li>
		      	<li>Pemeran Utama Pementasan Teater Biru Merah di UIAW 2017</li>
		      	<li>Pemeran Pendukung Pementasan Teater Pandora di GIK 2018</li>
		      	<li>Pemeran Cameo Pementasan TGB 2018</li>
		      	<li>Sutradara Pementasan Teater Biru Merah di UIAW 2018</li>
		      	<li>Sutradara Film Pendek Aku Bukan Teroris 2016</li>
		      	<li>Sutradara Film Pendek Deadline 2016</li>
		      	<li>Sutradara Film Pendek Mimpi 2017</li>
		      	<li>Asisten Sutradara Film Pendek Dinding 2017</li>
		      	<li>Pemeran Pendukung Film Pendek OPSI 2018 </li>
		     
		      </ol>
			</div>
		</div>
	</div>
</div>
	
<script type="text/javascript" src="{% static 'jquery1.js' %}">
	</script>



</body>
</html>

story9_app/templates/bukumenarik.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<header>{% include "mynavbar.html" %}</header>
	<link rel="stylesheet" type="text/css" href="{% static 'mystyle.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Cairo|Cinzel|cighteous" rel="stylesheet">
	<title>Daftar Buku Menarik</title>
	<style type="text/css">
		h1{
			font-family: 'Cinzel',  sans-serif;
		}
		th{
			font-family: 'Cinzel';
		}
		td{

		}
		#Favourite{
			font-family: 'Cairo', cursive;
			font-size: 20px;

		}
	</style>
</head>
<body>
	<div class="row">
		<div class="col-sm-6">
			<h1>Daftar Buku Menarik Bulan ini</h1>
			<p1 id="Favourite">
				Jumlah favorit :
				<h1 id= "Jumlahfavorit"> 0</h1>
			</p1>
		</div>
		<div class="col-sm-6">
			<button class="btn btn-danger navbar-btn submit" id="quilting">Quilting</button>
			<button class="btn btn-danger navbar-btn submit" id="sutradara" >Sutradara</button>
			<button class="btn btn-danger navbar-btn submit" id="doktor">Doktor</button>

		</div>
	</div>
	
	<table class="table table-hover">
		<thead id="#atastable">
			<tr>
			  <th scope="col">No</th>
			  <th scope="col">Title</th>
			  <th scope="col">Author</th>
			  <th scope="col">Publisher</th>
			  <th scope="col">Thumbnail</th>
			  <th scope="col">Description</th>
			  <th scope="col">Page</th>
			  <th scope="col">Be My Favourite</th>
			</tr>
		</thead>
		<tbody id="isitable" >
			
		</tbody>
	</table>
	{% block scripts%}
	<script type="text/javascript">
		$(document).ready(function(){
			var id ;
			$(".submit").click(function(){
				//ambil id
				id = $(this).attr("id");	
				console.log(id);
				var $list = $('#isitable');
				console.log("masuk1")
//				ngeremove row yg sudah ada.
				$(".hore").remove();

				$.ajax({
					url: {% autoescape off %} {{ books }}+ id {% endautoescape %},
					//biar yang muncul nya itu link dari books nya
					dataType: 'json',
					success: function(data){
						console.log(data);
						console.log("masukdata");
						$.each(data.items,function(key,value){
							var xx;
							if (value.volumeInfo.hasOwnProperty('imageLinks')) {
								xx = value.volumeInfo.imageLinks.smallThumbnail;
							} else{
								xx = 'https://cdn-images-1.medium.com/max/1024/1*OQXqTrTpXynrt85LeuaCnA.jpeg" style="width:80px;height:80px;'
							}
							$list.append('<tr class="hore"><th scope="row">'+(key+1)+'</th>'+'<td>'+value.volumeInfo.title+'</td>'
								+'<td>'+value.volumeInfo.authors+'</td>'+'<td>'+value.volumeInfo.publisher+'</td>'
								+'<td>'+'<img src="'+xx+'">'+'</td>'+'<td>'+value.volumeInfo.description+'</td>'+'<td>'+value.volumeInfo.pageCount+'</td>'+ '<td> <img src= "https://cdn2.iconfinder.com/data/icons/ster-objects/154/favorite-favorites-favourite-star-512.png" style = "width:20px;height:20px;" id = "bintang'+(key+1)+'" onclick="handleClick(event)"></td> </tr>'

								);
						});
					}
				});
			
		});

			});
			
		var counter = 0;
		function handleClick(evt) {
		  var button = evt.target || evt.srcElement;
		  if (button.src == "https://cdn2.iconfinder.com/data/icons/ster-objects/154/favorite-favorites-favourite-star-512.png") {
		    button.src = "https://cdn4.iconfinder.com/data/icons/basic-dashboard/512/Basic_Dashboard_UI_favourite_star_award-512.png";
		    counter+=1;
		    $("#Jumlahfavorit").html(counter);
		  } else{//kalau sudah di klik dan berwarna di ubah ke biasa lagi
		  	button.src ="https://cdn2.iconfinder.com/data/icons/ster-objects/154/favorite-favorites-favourite-star-512.png";
		  	counter-=1;
		    $("#Jumlahfavorit").html(counter);
		  }
		}
	</script>
	{% endblock scripts %}


</body>
</html>

story9_app/templates/subscribe.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
	<header>{% include "mynavbar.html" %}</header>
	<link rel="stylesheet" type="text/css" href="{% static 'mystyle.css' %}">
	<title>Subcribe</title>
</head>
<body>
	<div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3" style="background-color:transparent" align="">
                <h2 align="center">Form Subscription</h2>
                <form method="post" id="formsubs" >
                    {% csrf_token %}
                    {{ form }}
                    <p id="info"></p>
                    <br>
                    <button type="submit" class="btn btn-primary pull-right" id="button-subs">Subscribe</button>

                </form>
            </div>
        </div>
    </div>

    <script type="text/javascript">
    	$(document).ready(function(){
    		var nama = false;
    		var email = false;
    		var password = false;
    		$("#button-subs").attr('disabled',true);
    		$("#id_nama").change(function(){
    			if($(this).val() != ''){
    				nama = true;
    			}else{
    				nama = false;
    			}
    			check();
    		});
    		$("#id_email").change(function(){
    			if($(this).val() != ''){
    				email = true;
    			}else{
    				email=false;
    			}
    			check();
    		});
    		$("#id_password").change(function(){
    			if($(this).val() != ''){
    				password = true;
    			}else{
    				password =false;
    			}
    			check();
    		});
    		

    		function check(){
    			if(nama && email && password){
    				$("#button-subs").attr('disabled',false);
    			}else{
    				$("#button-subs").attr('disabled',true);
    			}
    		}


    	});
    	$(document).on('blur','#id_email',function(e){
    		e.preventDefault();
    		$.ajax({
    			url:'/story9/validasi/'+ $('#id_email').val(), //kalau error subscribeyuk aja atau pake bahasa django itu

    			success:function(data){
    				if(data.ada){
    					$("#info").html(data.message);
    					$("#button-subs").attr('disabled',true);
    				}else{
    					$("#info").html(data.message);
    					$("#button-subs").attr('disabled',false);
    				}
    			}
    		});

    	});

    	$("#button-subs").click(function(e){
    		e.preventDefault();
    		var info = {
    			email:$('#id_email').val(),
    			nama:$('#id_nama').val(),
    			password:$('#id_password').val(),
    			csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
    		}
    		$.ajax({
    			type:'POST',
    			url:'/story9/subscribeclick/',
    			data:info,
    			success:function(data){
    				alert('kamu berhasil subscribe ini');
    				
    			}
    		});

    	});
    </script>
</body>
</html>